In [1]:
import pandas as pd 
data_path = './mimic-iii/'
diagnoses_icd = pd.DataFrame(pd.read_csv(data_path + 'diagnoses_icd.csv'))

In [2]:
diagnoses_icd

      row_id  subject_id  hadm_id  seq_num icd9_code   mimic_id
0     112344       10006   142345        1     99591  335981618
1     112345       10006   142345        2     99662  335981619
2     112346       10006   142345        3      5672  335981620
3     112347       10006   142345        4     40391  335981621
4     112348       10006   142345        5     42731  335981622
5     112349       10006   142345        6      4280  335981623
6     112350       10006   142345        7      4241  335981624
7     112351       10006   142345        8      4240  335981625
8     112352       10006   142345        9      2874  335981626
9     112353       10006   142345       10     03819  335981627
10    112354       10006   142345       11      7850  335981628
11    112355       10006   142345       12     E8791  335981629
12    112356       10006   142345       13      V090  335981630
13    112357       10006   142345       14     56211  335981631
14    112358       10006   142345       15     28529  335981632
15    112359       10006   142345       16     25000  335981633
16    112360       10006   142345       17     V5867  335981634
17    112361       10006   142345       18     E9342  335981635
18    112362       10006   142345       19     41401  335981636
19    112363       10006   142345       20      2749  335981637
20    112364       10006   142345       21      3051  335981638
21    112394       10011   105331        1       570  335982448
22    112395       10011   105331        2     07030  335982449
23    112396       10011   105331        3     07054  335982450
24    112397       10011   105331        4     30401  335982451
25    112398       10011   105331        5      2875  335982452
26    112399       10011   105331        6      2760  335982453
27    112410       10013   165520        1      0389  335983726
28    112411       10013   165520        2     41071  335983727
29    112412       10013   165520        3     78551  335983728
...      ...         ...      ...      ...       ...        ...
1731  397607       44212   163189       17      2839  336287443
1732  397608       44212   163189       18      5601  336287444
1733  397609       44212   163189       19     99592  336287445
1734  397610       44212   163189       20      0414  336287446
1735  397611       44212   163189       21     70703  336287447
1736  397612       44212   163189       22     70723  336287448
1737  397613       44212   163189       23      5711  336287449
1738  397614       44212   163189       24      5712  336287450
1739  397643       44222   192189        1     42781  336280934
1740  397644       44222   192189        2      5849  336280935
1741  397645       44222   192189        3     E9429  336280936
1742  397646       44222   192189        4     41401  336280937
1743  397647       44222   192189        5     40390  336280938
1744  397648       44222   192189        6      5853  336280939
1745  397649       44222   192189        7     25060  336280940
1746  397650       44222   192189        8      3572  336280941
1747  397651       44222   192189        9      2724  336280942
1748  397652       44222   192189       10      3320  336280943
1749  397653       44222   192189       11     72400  336280944
1750  397667       44228   103379        1     03842  336280958
1751  397668       44228   103379        2     78552  336280959
1752  397669       44228   103379        3       486  336280960
1753  397670       44228   103379        4     00845  336280961
1754  397671       44228   103379        5      1977  336280962
1755  397672       44228   103379        6      1561  336280963
1756  397673       44228   103379        7      1975  336280964
1757  397674       44228   103379        8     45182  336280965
1758  397675       44228   103379        9     99592  336280966
1759  397676       44228   103379       10      2449  336280967
1760  397677       44228   103379       11      2859  336280968

[1761 rows x 6 columns]