In [1]:
import pandas as pd

In [3]:
data_path = "./mimic-iii/"

In [4]:
inputevents_mv = pd.DataFrame(pd.read_csv(data_path + "inputevents_mv.csv"))

In [7]:
inputevents_mv.columns

Index(['row_id', 'subject_id', 'hadm_id', 'icustay_id', 'starttime', 'endtime',
       'itemid', 'amount', 'amountuom', 'rate', 'rateuom', 'storetime', 'cgid',
       'orderid', 'linkorderid', 'ordercategoryname',
       'secondaryordercategoryname', 'ordercomponenttypedescription',
       'ordercategorydescription', 'patientweight', 'totalamount',
       'totalamountuom', 'isopenbag', 'continueinnextdept', 'cancelreason',
       'statusdescription', 'comments_editedby', 'comments_canceledby',
       'comments_date', 'originalamount', 'originalrate', 'mimic_id'],
      dtype='object')

In [14]:
df = inputevents_mv.loc[:, ["subject_id", "hadm_id", "patientweight"]].drop_duplicates()
weight = df[df.duplicated(["subject_id"], keep=False)]
weight

       subject_id  hadm_id  patientweight
499         43881   167021           86.3
514         43881   172454           95.0
1198        44212   163189           92.0
1262        44212   163189           87.0
4919        42135   117105           58.6
5582        42135   102203           64.6
5811        41795   118192          139.0
5826        41795   138132          141.7
6276        41976   145024           73.4
6293        41976   151798           74.1
6335        41976   179418           74.8
6350        41976   155297           78.9
6425        41976   174863           77.7
6429        41976   125013           77.0
6442        41976   125013           70.0
6592        41976   180546           80.5
6626        41976   130681           72.8
6816        41976   152032           74.9
6892        41976   172082           75.8
7293        41976   176016           70.0
7908        41976   173269           76.6
8069        41976   125449           69.8
8141        41914   101361           65.0
8145        41914   101361           62.7
8626        40124   146893           47.4
8742        40124   126179           41.5
8808        40601   182879          139.9
8809        40601   182879          100.0
8900        40286   109698           48.0
8902        40286   109698           60.0
8946        42346   175880           83.0
8957        42346   180391           79.8
9072        40310   157609           74.5
9325        40310   186361           81.7
10936       43870   142633           61.5
10937       43870   142633           61.4
10962       44083   198330           99.6
11004       44083   131048           98.6
11013       44083   125157          105.0
11225       42281   195911           70.0
11703       42281   195911           69.8
12218       42321   114648           40.9
12219       42321   114648           48.6

In [16]:
weight.to_csv("weight.csv", index=None)