In [1]:
import pandas as pd 
data_path = "./mimic-iii/"
patients = pd.DataFrame(pd.read_csv(data_path + "patients.csv"))

In [2]:
patients.columns

Index(['row_id', 'subject_id', 'gender', 'dob', 'dod', 'dod_hosp', 'dod_ssn',
       'expire_flag', 'mimic_id'],
      dtype='object')

In [3]:
patients.loc[:, ["subject_id", "dob"]]

    subject_id                  dob
0        10006  2094-03-05 00:00:00
1        10011  2090-06-05 00:00:00
2        10013  2038-09-03 00:00:00
3        10017  2075-09-21 00:00:00
4        10019  2114-06-20 00:00:00
5        10026  1895-05-17 00:00:00
6        10027  2108-01-15 00:00:00
7        10029  2061-04-10 00:00:00
8        10032  2050-03-29 00:00:00
9        10033  2051-04-21 00:00:00
10       10035  2053-04-13 00:00:00
11       10036  1885-03-24 00:00:00
12       10038  2056-01-27 00:00:00
13       10040  2061-10-23 00:00:00
14       10042  2076-05-06 00:00:00
15       10043  2109-04-07 00:00:00
16       10044  2071-02-11 00:00:00
17       10045  2061-03-25 00:00:00
18       10046  2141-03-15 00:00:00
19       10056  2046-02-27 00:00:00
20       10059  2081-01-03 00:00:00
21       10061  2031-05-19 00:00:00
22       10064  2058-04-23 00:00:00
23       10065  2111-07-18 00:00:00
24       10067  2101-06-10 00:00:00
25       10069  2146-10-23 00:00:00
26       10074  2081-12-26 00:00:00
27       10076  2038-05-10 00:00:00
28       10083  2110-03-25 00:00:00
29       10088  2029-07-09 00:00:00
..         ...                  ...
70       42075  2086-02-04 00:00:00
71       42135  2083-09-20 00:00:00
72       42199  2044-06-27 00:00:00
73       42231  2016-12-05 00:00:00
74       42275  2058-08-04 00:00:00
75       42281  2051-03-23 00:00:00
76       42292  2098-04-29 00:00:00
77       42302  2074-09-29 00:00:00
78       42321  2041-05-16 00:00:00
79       42346  2072-12-03 00:00:00
80       42367  2060-02-12 00:00:00
81       42412  2079-01-29 00:00:00
82       42430  2061-12-10 00:00:00
83       42458  1846-07-21 00:00:00
84       43735  2046-07-05 00:00:00
85       43746  2029-12-07 00:00:00
86       43748  2099-09-02 00:00:00
87       43779  2097-01-07 00:00:00
88       43798  2136-07-29 00:00:00
89       43827  1876-07-14 00:00:00
90       43870  2097-05-16 00:00:00
91       43879  2051-07-25 00:00:00
92       43881  2051-03-24 00:00:00
93       43909  2073-11-22 00:00:00
94       43927  2104-02-12 00:00:00
95       44083  2057-11-15 00:00:00
96       44154  1878-05-14 00:00:00
97       44212  2078-06-16 00:00:00
98       44222  2107-06-27 00:00:00
99       44228  2112-10-22 00:00:00

[100 rows x 2 columns]